services:
  devkit:
    build:
      context: .
      dockerfile: autodrive_devkit.Dockerfile
    image: autodrive_f1tenth_api:dev
    container_name: autodrive_f1tenth_api
    network_mode: host
    ipc: host
    privileged: true
    gpus: all
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY:-}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./autodrive_devkit/ws:/home/autodrive_devkit/ws:rw
      - ./.colcon-cache:/home/autodrive_devkit/ws/.colcon-cache
    working_dir: /home/autodrive_devkit/ws

