name: autodrive-f1tenth-sim-racing

services:
  devkit:
    build:
      context: .
      dockerfile: autodrive_devkit.Dockerfile
    image: autodrive_f1tenth_api:dev
    container_name: devkit

    network_mode: host
    ipc: host
    privileged: true
    tty: true
    stdin_open: true
    restart: unless-stopped

    # GPUs NVIDIA (formato correto: cada item é um mapeamento)
    gpus:
      - driver: nvidia
        count: all
        capabilities: [gpu, utility, compute, video]

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute,display
      - XDG_RUNTIME_DIR=/tmp/runtime-root

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.XAuthority:ro
      - ./autodrive_devkit:/home/autodrive_devkit/src/autodrive_devkit:rw
      - ./.colcon-cache:/home/autodrive_devkit/.colcon-cache:rw

    working_dir: /home/autodrive_devkit
