<?xml version="1.0"?>
<robot name="f1tenth_car" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Propriedades (dimensões) em metros -->
  <xacro:property name="wheel_radius" value="0.034"/>       <!-- 3.4 cm :contentReference[oaicite:5]{index=5} -->
  <xacro:property name="wheel_width"  value="0.023"/>       <!-- 2.3 cm :contentReference[oaicite:6]{index=6} -->
  <xacro:property name="half_wheelbase" value="0.13"/>      <!-- Metade de 26 cm :contentReference[oaicite:7]{index=7} -->
  <xacro:property name="half_track" value="0.0835"/>        <!-- Metade de ~16.7 cm (centro a centro das rodas) -->
  <xacro:property name="chassis_length" value="0.38"/>      <!-- 38 cm :contentReference[oaicite:8]{index=8} -->
  <xacro:property name="chassis_width"  value="0.125"/>     <!-- 12.5 cm :contentReference[oaicite:9]{index=9} -->
  <xacro:property name="chassis_thickness" value="0.014"/>  <!-- 1.4 cm :contentReference[oaicite:10]{index=10} -->
  <xacro:property name="top_chassis_width" value="0.101"/>  <!-- 10.1 cm :contentReference[oaicite:11]{index=11} -->
  <xacro:property name="top_chassis_thickness" value="0.002"/> <!-- 0.2 cm :contentReference[oaicite:12]{index=12} -->
  <xacro:property name="ground_clearance" value="0.003"/>   <!-- 0.3 cm do chão ao chassi inferior :contentReference[oaicite:13]{index=13} -->
  <xacro:property name="top_chassis_height" value="0.069"/> <!-- 6.9 cm do chão ao topo do chassi sup. :contentReference[oaicite:14]{index=14} -->
  <xacro:property name="lidar_diameter" value="0.038"/>     <!-- 3.8 cm :contentReference[oaicite:15]{index=15} -->
  <xacro:property name="lidar_height" value="0.07"/>        <!-- 7 cm :contentReference[oaicite:16]{index=16} -->
  <xacro:property name="lidar_offset_x" value="0.10"/>      <!-- ~9 cm atrás do para-choque frontal (0.19-0.10 = 0.09 m):contentReference[oaicite:17]{index=17} -->
  <xacro:property name="lidar_base_z" value="0.073"/>       <!-- Base do LiDAR ~0.4 cm acima do topo do chassi sup. (para altura total ~14.3 cm):contentReference[oaicite:18]{index=18} -->

  <!-- Link principal do chassi (base_link) -->
  <link name="base_link">
    <!-- Geometria visual: chassi inferior (base) -->
    <visual>
      <origin xyz="0 0 ${ground_clearance + chassis_thickness/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_thickness}"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <!-- Geometria visual: chassi superior (placa superior) -->
    <visual>
      <origin xyz="0 0 ${top_chassis_height - ground_clearance - top_chassis_thickness/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${top_chassis_width} ${top_chassis_thickness}"/>
      </geometry>
      <material name="TransparentBlue">
        <color rgba="0.3 0.5 1.0 0.5"/>  <!-- azul translúcido -->
      </material>
    </visual>
    <!-- Geometria de colisão (opcional, usando caixa englobante do chassi inteiro) -->
    <collision>
      <origin xyz="0 0 ${ground_clearance + (top_chassis_height)/2}" rpy="0 0 0"/>
      <geometry>
        <!-- Caixa cobrindo todo o volume do robô aproximado -->
        <box size="${chassis_length} ${chassis_width} ${top_chassis_height}"/>
      </geometry>
    </collision>
    <!-- Inércia aproximada do chassi (massa ~2 kg distribuída) -->
    <inertial>
      <mass value="2.0"/>
      <origin xyz="0 0 ${top_chassis_height/2}" rpy="0 0 0"/>
      <inertia ixx="0.0034" ixy="0.0" ixz="0.0" iyy="0.025" iyz="0.0" izz="0.027"/>
    </inertial>
  </link>

  <!-- Links e juntas para as 4 rodas -->
  <!-- Roda Dianteira Esquerda -->
  <link name="wheel_front_left">
    <visual>
      <!-- Cylinder axis along Y (rotate 90deg about X to align eixo de rotação) -->
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
  </link>
  <joint name="joint_wheel_front_left" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_front_left"/>
    <origin xyz="${half_wheelbase} ${half_track} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>  <!-- eixo de rotação: eixo Y (esquerda-direita) -->
  </joint>

  <!-- Roda Dianteira Direita -->
  <link name="wheel_front_right">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
  </link>
  <joint name="joint_wheel_front_right" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_front_right"/>
    <origin xyz="${half_wheelbase} -${half_track} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Roda Traseira Esquerda -->
  <link name="wheel_rear_left">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
  </link>
  <joint name="joint_wheel_rear_left" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_rear_left"/>
    <origin xyz="-${half_wheelbase} ${half_track} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Roda Traseira Direita -->
  <link name="wheel_rear_right">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
  </link>
  <joint name="joint_wheel_rear_right" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_rear_right"/>
    <origin xyz="-${half_wheelbase} -${half_track} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Link do LiDAR (sensor no topo frontal) -->
  <link name="laser_link">
    <visual>
      <origin xyz="0 0 ${lidar_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_diameter/2}" length="${lidar_height}"/>
      </geometry>
      <material name="Red">
        <color rgba="1.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${lidar_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_diameter/2}" length="${lidar_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 ${lidar_height/2}" rpy="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
  </link>
  <joint name="joint_laser" type="fixed">
    <parent link="base_link"/>
    <child link="laser_link"/>
    <origin xyz="${lidar_offset_x} 0 ${lidar_base_z}" rpy="0 0 0"/>
  </joint>

  <!-- Link da IMU (fixo no chassi, centro do robô) -->
  <link name="imu_link">
    <!-- sem geometria visual -->
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
    </inertial>
  </link>
  <joint name="joint_imu" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${top_chassis_height/2}" rpy="0 0 0"/>
  </joint>
</robot>
