<?xml version="1.0"?>
<robot name="f1tenth_car" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Propriedades (dimensões) em metros -->
  <xacro:property name="wheel_radius" value="0.034"/>       <!-- 3.4 cm -->
  <xacro:property name="wheel_width"  value="0.023"/>       <!-- 2.3 cm -->
  <xacro:property name="half_wheelbase" value="0.13"/>      <!-- L total = 0.26 m -->
  <xacro:property name="half_track" value="0.0835"/>        <!-- ~16.7 cm / 2 -->
  <xacro:property name="chassis_length" value="0.38"/>      <!-- 38 cm -->
  <xacro:property name="chassis_width"  value="0.125"/>     <!-- 12.5 cm -->
  <xacro:property name="chassis_thickness" value="0.014"/>  <!-- 1.4 cm -->
  <xacro:property name="top_chassis_width" value="0.101"/>  <!-- 10.1 cm -->
  <xacro:property name="top_chassis_thickness" value="0.002"/> <!-- 0.2 cm -->
  <xacro:property name="ground_clearance" value="0.003"/>   <!-- 0.3 cm -->
  <xacro:property name="top_chassis_height" value="0.069"/> <!-- 6.9 cm -->
  <xacro:property name="lidar_diameter" value="0.038"/>     <!-- 3.8 cm -->
  <xacro:property name="lidar_height" value="0.07"/>        <!-- 7 cm -->
  <xacro:property name="lidar_offset_x" value="0.10"/>      <!-- ~0.09 m atrás da dianteira -->
  <xacro:property name="lidar_base_z" value="0.073"/>       <!-- base do LiDAR -->

  <!-- Link principal do chassi (base_link) -->
  <link name="base_link">
    <!-- Geometria visual: chassi inferior (base) -->
    <visual>
      <origin xyz="0 0 ${ground_clearance + chassis_thickness/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_thickness}"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <!-- Geometria visual: chassi superior (placa superior) -->
    <visual>
      <origin xyz="0 0 ${top_chassis_height - ground_clearance - top_chassis_thickness/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${top_chassis_width} ${top_chassis_thickness}"/>
      </geometry>
      <material name="TransparentBlue">
        <color rgba="0.3 0.5 1.0 0.5"/>
      </material>
    </visual>
    <!-- Geometria de colisão (caixa englobante) -->
    <collision>
      <origin xyz="0 0 ${ground_clearance + (top_chassis_height)/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${top_chassis_height}"/>
      </geometry>
    </collision>
    <!-- Inércia aproximada do chassi (massa ~2 kg) -->
    <inertial>
      <mass value="2.0"/>
      <origin xyz="0 0 ${top_chassis_height/2}" rpy="0 0 0"/>
      <inertia ixx="0.0034" ixy="0.0" ixz="0.0" iyy="0.025" iyz="0.0" izz="0.027"/>
    </inertial>
  </link>

  <!-- ========== MANGAS DE EIXO (esterço dianteiro) ========== -->
  <link name="steer_front_left_link">
    <inertial>
      <mass value="0.02"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
  </link>
  <joint name="joint_steer_front_left" type="revolute">
    <parent link="base_link"/>
    <child link="steer_front_left_link"/>
    <origin xyz="${half_wheelbase} ${half_track} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="5.0" lower="-0.7" upper="0.7" velocity="2.0"/>
  </joint>

  <link name="steer_front_right_link">
    <inertial>
      <mass value="0.02"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
  </link>
  <joint name="joint_steer_front_right" type="revolute">
    <parent link="base_link"/>
    <child link="steer_front_right_link"/>
    <origin xyz="${half_wheelbase} -${half_track} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="5.0" lower="-0.7" upper="0.7" velocity="2.0"/>
  </joint>

  <!-- ========== Rodas ========== -->
  <!-- Dianteira Esquerda -->
  <link name="wheel_front_left">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
  </link>
  <joint name="joint_wheel_front_left" type="continuous">
    <parent link="steer_front_left_link"/>
    <child link="wheel_front_left"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Dianteira Direita -->
  <link name="wheel_front_right">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
  </link>
  <joint name="joint_wheel_front_right" type="continuous">
    <parent link="steer_front_right_link"/>
    <child link="wheel_front_right"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Traseira Esquerda -->
  <link name="wheel_rear_left">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
  </link>
  <joint name="joint_wheel_rear_left" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_rear_left"/>
    <origin xyz="-${half_wheelbase} ${half_track} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Traseira Direita -->
  <link name="wheel_rear_right">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
  </link>
  <joint name="joint_wheel_rear_right" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_rear_right"/>
    <origin xyz="-${half_wheelbase} -${half_track} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- GAZEBO PLUGINS FOR THE SIMULATION -->

  <!-- Link do LiDAR -->
  <link name="laser_link">
    <visual>
      <origin xyz="0 0 ${lidar_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_diameter/2}" length="${lidar_height}"/>
      </geometry>
      <material name="Red">
        <color rgba="1.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${lidar_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_diameter/2}" length="${lidar_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 ${lidar_height/2}" rpy="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
  </link>
  <joint name="joint_laser" type="fixed">
    <parent link="base_link"/>
    <child link="laser_link"/>
    <origin xyz="${lidar_offset_x} 0 ${lidar_base_z}" rpy="0 0 0"/>
  </joint>

  <!-- Link da IMU -->
  <link name="imu_link">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
    </inertial>
  </link>
  <joint name="joint_imu" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${top_chassis_height/2}" rpy="0 0 0"/>
  </joint>



  <!-- ========== RGB-D CAMERA (para RTAB-MAP) ========== -->
  <link name="front_camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 0.03"/>
      </geometry>
      <material name="DarkGray">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
    <inertial>
      <mass value="0.02"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
    </inertial>
  </link>

  <joint name="joint_front_camera" type="fixed">
    <parent link="base_link"/>
    <child link="front_camera_link"/>
    <!-- Movida mais à frente do LIDAR -->
    <origin xyz="${lidar_offset_x + 0.075} 0 ${lidar_base_z - 0.02}" rpy="0 0 0"/>
  </joint>


    <!-- ======== GAZEBO: SENSOR LiDAR NO laser_link (publica /scan) ======== -->
  <gazebo reference="laser_link">
    <sensor name="lidar_sensor" type="ray">
      <always_on>true</always_on>
      <update_rate>20</update_rate>
      <visualize>false</visualize>

      <!-- Geometria do feixe -->
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>            <!-- ~0,5° por feixe -->
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>   <!-- -180° -->
            <max_angle> 3.14159</max_angle>   <!-- +180° -->
          </horizontal>
        </scan>
        <range>
          <min>0.05</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>

      <!-- Plugin ROS 2 para publicar LaserScan -->
      <plugin name="gazebo_ros_laser" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <!-- publica diretamente em /scan -->
          <remapping>~/out:=/scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>


  <!-- ======== GAZEBO: SENSOR IMU NO imu_link ======== -->
  <gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>false</visualize>

      <!-- Plugin ROS 2 (Gazebo Classic) -->
      <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
        <ros>
          <!-- publica em /imu/data -->
          <remapping>~/out:=/imu/data</remapping>
        </ros>
        <frame_name>imu_link</frame_name>
      </plugin>

      <!-- Ruído realista (ajuste se quiser mais “limpo”) -->
      <imu>
        <angular_velocity>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean><stddev>0.001</stddev>
              <bias_mean>0.0</bias_mean><bias_stddev>0.0002</bias_stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean><stddev>0.001</stddev>
              <bias_mean>0.0</bias_mean><bias_stddev>0.0002</bias_stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean><stddev>0.001</stddev>
              <bias_mean>0.0</bias_mean><bias_stddev>0.0002</bias_stddev>
            </noise>
          </z>
        </angular_velocity>
        <linear_acceleration>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean><stddev>0.1</stddev>
              <bias_mean>0.0</bias_mean><bias_stddev>0.02</bias_stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean><stddev>0.1</stddev>
              <bias_mean>0.0</bias_mean><bias_stddev>0.02</bias_stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean><stddev>0.1</stddev>
              <bias_mean>0.0</bias_mean><bias_stddev>0.02</bias_stddev>
            </noise>
          </z>
        </linear_acceleration>
      </imu>
    </sensor>
  </gazebo>

  <!-- Sensor de câmera RGB-D -->
  <gazebo reference="front_camera_link">

    <!-- Câmera RGB -->
    <sensor name="front_camera_rgb" type="camera">
      <always_on>true</always_on>
      <update_rate>30.0</update_rate>
      <camera>
        <horizontal_fov>1.3962634</horizontal_fov> <!-- ~80° -->
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>50.0</far>
        </clip>
      </camera>
      <plugin name="front_camera_rgb_plugin" filename="libgazebo_ros_camera.so">
        <ros>
          <remapping>~/image_raw:=/autodrive/f1tenth_1/front_camera/image_raw</remapping>
          <remapping>~/camera_info:=/autodrive/f1tenth_1/front_camera/camera_info</remapping>
        </ros>
        <frame_name>front_camera_link</frame_name>
      </plugin>
    </sensor>

    <!-- Câmera Depth (simulada via sensor de profundidade) -->
    <sensor name="front_camera_depth" type="depth">
      <always_on>true</always_on>
      <update_rate>30.0</update_rate>
      <camera>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>FLOAT32</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>20.0</far>
        </clip>
      </camera>
      <plugin name="front_camera_depth_plugin" filename="libgazebo_ros_depth_camera.so">
        <ros>
          <remapping>~/image_raw:=/autodrive/f1tenth_1/front_camera/depth/image_raw</remapping>
          <remapping>~/camera_info:=/autodrive/f1tenth_1/front_camera/depth/camera_info</remapping>
        </ros>
        <frame_name>front_camera_link</frame_name>
      </plugin>
    </sensor>

  </gazebo>

  <gazebo>
    <plugin name="f1tenth_ackermann" filename="libgazebo_ros_ackermann_drive.so">
      <ros>
        <remapping>cmd_vel:=/cmd_vel</remapping>
        <remapping>odom:=/odom</remapping>
      </ros>
      <update_rate>100.0</update_rate>
      <front_left_joint>joint_wheel_front_left</front_left_joint>
      <front_right_joint>joint_wheel_front_right</front_right_joint>
      <rear_left_joint>joint_wheel_rear_left</rear_left_joint>
      <rear_right_joint>joint_wheel_rear_right</rear_right_joint>
      <left_steering_joint>joint_steer_front_left</left_steering_joint>
      <right_steering_joint>joint_steer_front_right</right_steering_joint>
      <max_steer>0.698</max_steer>
      <max_speed>2.0</max_speed>
      <!-- ativa publicação de odom e TF -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>false</publish_odom_tf>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>
  </gazebo>

</robot>
